import {
  Wallet,
  ShoppingCart,
  Home,
  Car,
  Coffee,
  Utensils,
  Plane,
  Heart,
  Shirt,
  Gamepad2,
  GraduationCap,
  Stethoscope,
  DollarSign,
  Gift,
  Music,
  Film,
  Dumbbell,
  PiggyBank,
  TrendingUp,
  CreditCard,
  Building,
  Building2,
  Briefcase,
  Smartphone,
  Laptop,
  Wifi,
  Zap,
  Droplet,
  Flame,
  Snowflake,
  Bus,
  Train,
  Fuel,
  ShoppingBag,
  Pizza,
  Beer,
  IceCream,
  Cake,
  type LucideIcon,
} from 'lucide-react';

export interface IconConfig {
  name: string;
  component: LucideIcon;
  tags: string[];
}

export const ICONS: IconConfig[] = [
  { name: 'Wallet', component: Wallet, tags: ['finance', 'money', 'payment'] },
  { name: 'DollarSign', component: DollarSign, tags: ['finance', 'money', 'currency'] },
  { name: 'CreditCard', component: CreditCard, tags: ['finance', 'payment', 'card'] },
  { name: 'PiggyBank', component: PiggyBank, tags: ['finance', 'savings', 'money'] },
  { name: 'TrendingUp', component: TrendingUp, tags: ['finance', 'investment', 'growth'] },
  { name: 'ShoppingCart', component: ShoppingCart, tags: ['shopping', 'retail', 'purchase'] },
  { name: 'ShoppingBag', component: ShoppingBag, tags: ['shopping', 'retail', 'purchase'] },
  { name: 'Home', component: Home, tags: ['housing', 'rent', 'mortgage'] },
  { name: 'Building', component: Building, tags: ['housing', 'office', 'property'] },
  { name: 'Building2', component: Building2, tags: ['housing', 'apartment', 'property'] },
  { name: 'Car', component: Car, tags: ['transport', 'vehicle', 'auto'] },
  { name: 'Bus', component: Bus, tags: ['transport', 'public', 'commute'] },
  { name: 'Train', component: Train, tags: ['transport', 'public', 'commute'] },
  { name: 'Plane', component: Plane, tags: ['travel', 'transport', 'flight'] },
  { name: 'Fuel', component: Fuel, tags: ['transport', 'gas', 'auto'] },
  { name: 'Coffee', component: Coffee, tags: ['food', 'drink', 'cafe'] },
  { name: 'Utensils', component: Utensils, tags: ['food', 'dining', 'restaurant'] },
  { name: 'Pizza', component: Pizza, tags: ['food', 'dining', 'takeout'] },
  { name: 'Beer', component: Beer, tags: ['food', 'drink', 'bar'] },
  { name: 'IceCream', component: IceCream, tags: ['food', 'dessert', 'treat'] },
  { name: 'Cake', component: Cake, tags: ['food', 'dessert', 'celebration'] },
  { name: 'Heart', component: Heart, tags: ['health', 'medical', 'wellness'] },
  { name: 'Stethoscope', component: Stethoscope, tags: ['health', 'medical', 'doctor'] },
  { name: 'Dumbbell', component: Dumbbell, tags: ['health', 'fitness', 'gym'] },
  { name: 'Shirt', component: Shirt, tags: ['clothing', 'fashion', 'apparel'] },
  { name: 'Gamepad2', component: Gamepad2, tags: ['entertainment', 'gaming', 'hobby'] },
  { name: 'Music', component: Music, tags: ['entertainment', 'audio', 'hobby'] },
  { name: 'Film', component: Film, tags: ['entertainment', 'movies', 'media'] },
  { name: 'Gift', component: Gift, tags: ['celebration', 'present', 'event'] },
  { name: 'GraduationCap', component: GraduationCap, tags: ['education', 'school', 'learning'] },
  { name: 'Briefcase', component: Briefcase, tags: ['work', 'business', 'career'] },
  { name: 'Smartphone', component: Smartphone, tags: ['technology', 'phone', 'mobile'] },
  { name: 'Laptop', component: Laptop, tags: ['technology', 'computer', 'work'] },
  { name: 'Wifi', component: Wifi, tags: ['technology', 'internet', 'utility'] },
  { name: 'Zap', component: Zap, tags: ['utility', 'electricity', 'power'] },
  { name: 'Droplet', component: Droplet, tags: ['utility', 'water', 'bills'] },
  { name: 'Flame', component: Flame, tags: ['utility', 'gas', 'heating'] },
  { name: 'Snowflake', component: Snowflake, tags: ['utility', 'cooling', 'ac'] },
];
